package day23;

public class ExceptionDemo4 {
	public static void main(String[] args) {
try {//try always lead catch. Try catch can be nested as many times as requirement.
	
} catch (Exception e) {//Ccatch comes immediately after try.catch always lead finally
	
}finally {//finally comes immediately after catch or try but never before catch. any resources class that has to be closed is put inside finally. try finally can also be used escaping catch block
	
}
	}


}
